/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.*;
import Code.Product.ProType;
import static Code.Product.ProType.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author internet
 */
public class Employee extends javax.swing.JFrame {
    
    private int empId = 0 ;
    /**
     * Creates new form Employee
     */
    private DefaultTableModel model;
    public Employee() {
        initComponents();
        model = (DefaultTableModel) jTable2.getModel(); 
        setLocationRelativeTo(null);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        price = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Type = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Det = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Cost = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        amount = new javax.swing.JSpinner();
        EmpName = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("EMPLOYEE");

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });

        jLabel3.setText("Name : ");

        jLabel4.setText("Price : ");

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Name", "Detail", "Type", "Price", "Cost", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stationery", "Electronics", "Equipment", "MusicAndGame", "Costume", "Other" }));

        jLabel5.setText("Type : ");

        jLabel6.setText("Detail : ");

        Det.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetActionPerformed(evt);
            }
        });

        jLabel7.setText("Cost : ");

        Cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostActionPerformed(evt);
            }
        });

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        jLabel2.setText("Amount :");

        EmpName.setText("Name ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(85, 85, 85))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47)
                                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)))
                            .addGap(70, 70, 70))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Det, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Cost, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EmpName)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Det, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EmpName))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);  //เมื่อกด logout ให้เปิดหน้า login แล้วปิดหน้านี้
        this.dispose();
        System.out.println("Emp logout");
    }//GEN-LAST:event_LogoutActionPerformed

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed
    public void setId(int id) throws ClassNotFoundException, SQLException{
        empId = id;    //เหมือน setId ใน Customer ลดบางส่วนออก
        Connection con = ConnectionBuilder.connect();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("Select empName from Employee where empId = "+empId);
        rs.next();
        EmpName.setText(rs.getString(1));
        con.close();
    }
    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // เมื่อกดแอดสินค้า
        
        String type = null;

        try {
            Connection con = ConnectionBuilder.connect(); //เชื่อมต่อ Database
            PreparedStatement ps = con.prepareStatement("insert into Product(proname,det,protype,proprice,procost,addpro,amount)"
                    + " values(?,?,?,?,?,?,?)");
            if (Type.getSelectedItem().equals("Stationery")) {  // เช็ค Type ของสินค้าว่าเลือกอันไหนอยู่
                type = (String) Type.getSelectedItem();
            } else if (Type.getSelectedItem().equals("Electronics")) {
                type = (String) Type.getSelectedItem();
            } else if (Type.getSelectedItem().equals("Equipment")) {
                type = (String) Type.getSelectedItem();
            } else if (Type.getSelectedItem().equals("Costume")) {
                type = (String) Type.getSelectedItem();
            } else if (Type.getSelectedItem().equals("MusicAndGame")) {
                type = (String) Type.getSelectedItem();
            } else if (Type.getSelectedItem().equals("Other")) {
                type = (String) Type.getSelectedItem();
            }
            double d = Double.parseDouble(price.getText());  // เอา Text ของราคามาแปลงเป็น Double เพื่อให้เข้ากับ Database ได้
            double c = Double.parseDouble(Cost.getText());
            PreparedStatement ps2 = con.prepareStatement("Select amount from product where proname = '"+Name.getText()+"' and det = '"+Det.getText()+"' and proPrice = " + d);
            ResultSet rs = ps2.executeQuery();  //เอาค่าจำนวนของสินค่าใน Product ที่มีชื่อเหมือนค่าที่พิมพ์ ราตาเท่ากัน และ รายละเอียดเหมือนกัน (มองว่าเป็นสินค่าตัวเดียวกัน)
            PreparedStatement ps3 = con.prepareStatement("UPDATE product SET amount = ? WHERE proName = ? and proPrice = ? and det = ?");
            //long l = Long.parseLong(productID.getText());
            //long l = proId;
            //System.out.println(d + " " + proprice);
            if (rs.next()){ //เช็คว่าสินค่าที่จะแอดเป็นสินค่าที่มีอยู่แล้วหรือไม่ ดูจากว่าใน ResultSet มีค่าหรือไม่ (เปรียบเทียบใน where sql)
                int i = rs.getInt("amount")+(int)amount.getValue();  // เอาค่าที่มีอยู่แล้ว บวกกับที่แอดสินค้าเข้าไปใหม่
                ps3.setInt(1, i);      // ใส่ค่าทีละช่อง
                ps3.setString(2,Name.getText());
                ps3.setDouble(3,d);
                ps3.setString(4,Det.getText());
                ps3.executeUpdate(); 
                System.out.println("Change amount success");
                con.close();
            } else {  //เป็นสินค้าใหม่ ไม่เคยมีในตาราง Product มาก่อน
                int newAmount = (int)amount.getValue();  // ใส่ค่าทีละช่อง
                ps.setString(1, Name.getText());
                ps.setString(2, Det.getText());
                ps.setString(3, type);
                ps.setDouble(4, d);
                ps.setDouble(5, c);
                ps.setInt(6, this.empId);
                ps.setInt(7, newAmount);
                if (newAmount<=0){  // เช็คว่าถ้าจำนวน <0 ให้แจ้งเตือน เพราะว่าสินค้าจำนวนติดลบไม่ได้
                    amount.requestFocus();
                    JOptionPane.showMessageDialog(null, "Change amount and try again", "Err", JOptionPane.ERROR_MESSAGE);
                }
                else { //จำนวนสินค้าปกติ แอดได้
                    ps.executeUpdate();
                    con.close();
                    System.out.println("Add product Success");
                }    
            }
            formWindowOpened(null);
            //Employee e = new Employee();   //สร้าง Employee ขึ้นมาใหม่ (จะรีเฟรซตาราง) [[จริงๆเรียกเมธอด formWindowOpened ได้]]
            //e.setId(empId);   // ส่ง empId ไปให้ empใหม่ เหมือนเป็นการ login ยูเซอร์เดิมเพราะยังไม่ได้ออกจากระบบ
            //e.setVisible(true);
            //this.dispose();
            
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Price or cost must not number", "Err", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_AddActionPerformed

    private void DetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DetActionPerformed

    private void CostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // เมื่อเปิดหน้าต่าง
        try{  //เพิ่มข้อมูลในตารางหน้า Employee (เหมือนใน Customer แต่ข้อมูลมากกว่า)
            int totalRow = jTable2.getRowCount() - 1;  
            while (totalRow > -1){
                model.removeRow(totalRow--);
            }
            
            Connection con = ConnectionBuilder.connect();
            PreparedStatement ps = con.prepareStatement("Select * From product");
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                Vector row = new Vector();
                row.add(rs.getLong("proid"));
                row.add(rs.getString("proname"));
                row.add(rs.getString("det"));
                row.add(rs.getString("protype"));
                row.add(rs.getDouble("proprice"));
                row.add(rs.getDouble("procost"));
                row.add(rs.getInt("Amount"));
                
                model.addRow(row);
            }
            jTable2.setModel(model);
        } catch (Exception ex) {
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_formWindowOpened

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // เมื่อเลือกอันใดอันนึง ในตารางหน้า Employee 
        int i = jTable2.getSelectedRow();     //เช็คว่าเลือก row ไหน
        TableModel model = jTable2.getModel();
        Name.setText(model.getValueAt(i, 1).toString());  //เอาค่าของแต่ละ column มาแสดงในช่องด้านข้าง
        Det.setText(model.getValueAt(i, 2).toString());
        Type.setSelectedItem(model.getValueAt(i, 3));
        price.setText(model.getValueAt(i, 4).toString());
        Cost.setText(model.getValueAt(i, 5).toString());
        String a = model.getValueAt(i,6).toString();
        int b = Integer.parseInt(a);
        amount.setModel(new javax.swing.SpinnerNumberModel(b, -b, 50, 1));  // setAmount
    }//GEN-LAST:event_jTable2MouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // เมื่อกดปุ่ม Delete
        try{
            int index = jTable2.getSelectedRow();   
            String id = jTable2.getValueAt(index, 0).toString();
            
            String sql = "delete from product where proid = "+id;
            ConnectionBuilder.connect().prepareStatement(sql).executeUpdate();  // เชื่อมต่อ Database ใส่ sql ลบข้อมูล
            System.out.println("Delete Product " + id + " Success");
            formWindowOpened(null);  // รีเฟรชตารางใหม่
            // ถ้าสินค้าอยู่ใน Cart หรือมีลูกค้าซื้อไปแล้ว จะลบไม่ได้ เพราะว่า product Id ลิงค์อยู่ ให้ไป setAmount ให้เป็น 0 แทน 
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Cost;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Det;
    private javax.swing.JLabel EmpName;
    private javax.swing.JButton Logout;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JSpinner amount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
